"""fix unique active ticket constraint

Revision ID: 26586ad62b8f
Revises: 20260429_0004
Create Date: 2026-04-29 16:23:43.535198
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '26586ad62b8f'
down_revision = '20260429_0004'
branch_labels = None
depends_on = None


def _index_exists(inspector: sa.Inspector, table_name: str, index_name: str) -> bool:
    return any(index["name"] == index_name for index in inspector.get_indexes(table_name))


def upgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    dialect = bind.dialect.name

    if dialect == "sqlite":
        if not _index_exists(inspector, 'reports', op.f('ix_reports_violation_type')):
            op.create_index(op.f('ix_reports_violation_type'), 'reports', ['violation_type'], unique=False)
        if not _index_exists(inspector, 'traffic_tickets', 'ix_unique_active_evidence_ticket'):
            op.create_index(
                'ix_unique_active_evidence_ticket',
                'traffic_tickets',
                ['evidence_report_id'],
                unique=True,
                sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"),
            )
        if not _index_exists(inspector, 'traffic_tickets', 'ix_unique_active_legacy_ticket'):
            op.create_index(
                'ix_unique_active_legacy_ticket',
                'traffic_tickets',
                ['report_id'],
                unique=True,
                sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"),
            )
        return

    # ### commands auto generated by Alembic - adjusted for PostgreSQL ###
    op.alter_column('reports', 'status',
               existing_type=postgresql.ENUM('SUBMITTED', 'AI_PROCESSING', 'UNDER_REVIEW', 'VALIDATED', 'REJECTED', name='statusenum'),
               type_=sa.Enum('SUBMITTED', 'AI_PROCESSING', 'UNDER_REVIEW', 'VALIDATED', 'REJECTED', 'CLOSED', name='reportstatusenum', native_enum=False),
               existing_nullable=True)
    op.create_index(op.f('ix_reports_violation_type'), 'reports', ['violation_type'], unique=False)
    op.alter_column('traffic_tickets', 'officer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('traffic_tickets', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('traffic_tickets', 'penal_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('traffic_tickets', 'fine_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('traffic_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('traffic_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=False)
    op.drop_constraint(op.f('traffic_tickets_report_id_key'), 'traffic_tickets', type_='unique')
    op.create_index('ix_unique_active_evidence_ticket', 'traffic_tickets', ['evidence_report_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"), sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"))
    op.create_index('ix_unique_active_legacy_ticket', 'traffic_tickets', ['report_id'], unique=True, postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"), sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"))
    op.create_unique_constraint(None, 'traffic_tickets', ['ticket_number'])
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('CITIZEN', 'POLICE', 'ADMIN', name='roleenum'),
               type_=sa.Enum('CITIZEN', 'POLICE', 'ADMIN', name='roleenum', native_enum=False),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    dialect = bind.dialect.name

    if dialect == "sqlite":
        if _index_exists(inspector, 'traffic_tickets', 'ix_unique_active_legacy_ticket'):
            op.drop_index('ix_unique_active_legacy_ticket', table_name='traffic_tickets')
        if _index_exists(inspector, 'traffic_tickets', 'ix_unique_active_evidence_ticket'):
            op.drop_index('ix_unique_active_evidence_ticket', table_name='traffic_tickets')
        if _index_exists(inspector, 'reports', op.f('ix_reports_violation_type')):
            op.drop_index(op.f('ix_reports_violation_type'), table_name='reports')
        return

    # ### commands auto generated by Alembic - adjusted for PostgreSQL ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('CITIZEN', 'POLICE', 'ADMIN', name='roleenum', native_enum=False),
               type_=postgresql.ENUM('CITIZEN', 'POLICE', 'ADMIN', name='roleenum'),
               existing_nullable=True)
    op.drop_constraint(None, 'traffic_tickets', type_='unique')
    op.drop_index('ix_unique_active_legacy_ticket', table_name='traffic_tickets', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"), sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"))
    op.drop_index('ix_unique_active_evidence_ticket', table_name='traffic_tickets', postgresql_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"), sqlite_where=sa.text("status NOT IN ('CANCELLED', 'CLOSED')"))
    op.create_unique_constraint(op.f('traffic_tickets_report_id_key'), 'traffic_tickets', ['report_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('traffic_tickets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               nullable=True)
    op.alter_column('traffic_tickets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('traffic_tickets', 'fine_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('traffic_tickets', 'penal_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('traffic_tickets', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'ISSUED'::character varying"),
               existing_nullable=False)
    op.alter_column('traffic_tickets', 'officer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_reports_violation_type'), table_name='reports')
    op.alter_column('reports', 'status',
               existing_type=sa.Enum('SUBMITTED', 'AI_PROCESSING', 'UNDER_REVIEW', 'VALIDATED', 'REJECTED', 'CLOSED', name='reportstatusenum', native_enum=False),
               type_=postgresql.ENUM('SUBMITTED', 'AI_PROCESSING', 'UNDER_REVIEW', 'VALIDATED', 'REJECTED', name='statusenum'),
               existing_nullable=True)
    # ### end Alembic commands ###
