"""Add FineRule model

Revision ID: 4b0fb4e42570
Revises: 59daecb0716e
Create Date: 2026-04-30 09:52:35.823566
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4b0fb4e42570'
down_revision = '59daecb0716e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
