"""add fine rules engine

Revision ID: 59daecb0716e
Revises: 26586ad62b8f
Create Date: 2026-04-29 16:33:07.947104
"""
from alembic import op
import sqlalchemy as sa
import uuid
from datetime import datetime



# revision identifiers, used by Alembic.
revision = '59daecb0716e'
down_revision = '26586ad62b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('violation_type', sa.String(), nullable=False),
    sa.Column('penal_code', sa.String(), nullable=False),
    sa.Column('fine_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fine_rules_violation_type'), 'fine_rules', ['violation_type'], unique=False)
    op.add_column('traffic_tickets', sa.Column('fine_rule_id', sa.String(), nullable=True))
    op.add_column('traffic_tickets', sa.Column('fine_rule_version', sa.Integer(), nullable=True))
    op.add_column('traffic_tickets', sa.Column('fine_override_reason', sa.Text(), nullable=True))
    op.create_foreign_key('fk_traffic_tickets_fine_rule_id', 'traffic_tickets', 'fine_rules', ['fine_rule_id'], ['id'])
    
    # --- Seed Data ---
    fine_rules_table = sa.table('fine_rules',
        sa.column('id', sa.String),
        sa.column('violation_type', sa.String),
        sa.column('penal_code', sa.String),
        sa.column('fine_amount', sa.Float),
        sa.column('currency', sa.String),
        sa.column('description', sa.Text),
        sa.column('severity', sa.String),
        sa.column('active', sa.Boolean),
        sa.column('version', sa.Integer),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    
    op.bulk_insert(fine_rules_table, [
        {
            'id': str(uuid.uuid4()), 'violation_type': 'helmet', 'penal_code': 'MV-ACT-2007-S129', 'fine_amount': 2500.0,
            'currency': 'LKR', 'description': 'Riding a motorcycle without a protective helmet', 'severity': 'MEDIUM', 
            'active': True, 'version': 1, 'created_at': datetime.utcnow(), 'updated_at': datetime.utcnow()
        },
        {
            'id': str(uuid.uuid4()), 'violation_type': 'red-light', 'penal_code': 'MV-ACT-2007-S140', 'fine_amount': 3000.0,
            'currency': 'LKR', 'description': 'Failing to comply with traffic light signals', 'severity': 'HIGH', 
            'active': True, 'version': 1, 'created_at': datetime.utcnow(), 'updated_at': datetime.utcnow()
        },
        {
            'id': str(uuid.uuid4()), 'violation_type': 'white-line', 'penal_code': 'MV-ACT-2007-S145', 'fine_amount': 1500.0,
            'currency': 'LKR', 'description': 'Crossing or driving on the continuous white line', 'severity': 'LOW', 
            'active': True, 'version': 1, 'created_at': datetime.utcnow(), 'updated_at': datetime.utcnow()
        }
    ])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_traffic_tickets_fine_rule_id', 'traffic_tickets', type_='foreignkey')
    op.drop_column('traffic_tickets', 'fine_override_reason')
    op.drop_column('traffic_tickets', 'fine_rule_version')
    op.drop_column('traffic_tickets', 'fine_rule_id')
    op.drop_index(op.f('ix_fine_rules_violation_type'), table_name='fine_rules')
    op.drop_table('fine_rules')
    # ### end Alembic commands ###
